// import prodktMotion from "./apps/www/motion";

import type { Config } from "tailwindcss"

import prodktMotion from "./apps/www/motion/index.js"

const {
  keyframes,
  accentColor,
  accessibility,
  alignContent,
  alignItems,
  alignSelf,
  animation,
  appearance,
  aspectRatio,
  backdropBlur,
  backdropBrightness,
  backdropContrast,
  backdropFilter,
  backdropGrayscale,
  backdropHueRotate,
  backdropInvert,
  backdropOpacity,
  backdropSaturate,
  backdropSepia,
  backgroundAttachment,
  backgroundBlendMode,
  backgroundClip,
  backgroundColor,
  backgroundImage,
  backgroundOpacity,
  backgroundOrigin,
  backgroundPosition,
  backgroundRepeat,
  backgroundSize,
  blur,
  borderCollapse,
  borderColor,
  borderOpacity,
  borderRadius,
  borderSpacing,
  borderStyle,
  borderWidth,
  boxDecorationBreak,
  boxShadow,
  boxShadowColor,
  boxSizing,
  breakAfter,
  breakBefore,
  breakInside,
  brightness,
  captionSide,
  caretColor,
  clear,
  columns,
  contain,
  container,
  content,
  contrast,
  cursor,
  display,
  divideColor,
  divideOpacity,
  divideStyle,
  divideWidth,
  dropShadow,
  fill,
  filter,
  flex,
  flexBasis,
  flexDirection,
  flexGrow,
  flexShrink,
  flexWrap,
  float,
  fontFamily,
  fontSize,
  fontSmoothing,
  fontStyle,
  fontVariantNumeric,
  fontWeight,
  forcedColorAdjust,
  gap,
  gradientColorStops,
  grayscale,
  gridAutoColumns,
  gridAutoFlow,
  gridAutoRows,
  gridColumn,
  gridColumnEnd,
  gridColumnStart,
  gridRow,
  gridRowEnd,
  gridRowStart,
  gridTemplateColumns,
  gridTemplateRows,
  height,
  hueRotate,
  hyphens,
  inset,
  invert,
  isolation,
  justifyContent,
  justifyItems,
  justifySelf,
  letterSpacing,
  lineClamp,
  lineHeight,
  listStyleImage,
  listStylePosition,
  listStyleType,
  margin,
  maxHeight,
  maxWidth,
  minHeight,
  minWidth,
  mixBlendMode,
  objectFit,
  objectPosition,
  opacity,
  order,
  outlineColor,
  outlineOffset,
  outlineStyle,
  outlineWidth,
  overflow,
  overscrollBehavior,
  padding,
  placeContent,
  placeItems,
  placeSelf,
  placeholderColor,
  placeholderOpacity,
  pointerEvents,
  position,
  preflight,
  resize,
  ringColor,
  ringOffsetColor,
  ringOffsetWidth,
  ringOpacity,
  ringWidth,
  rotate,
  saturate,
  scale,
  scrollBehavior,
  scrollMargin,
  scrollPadding,
  scrollSnapAlign,
  scrollSnapStop,
  scrollSnapType,
  sepia,
  size,
  skew,
  space,
  stroke,
  spacing,
  strokeWidth,
  tableLayout,
  textAlign,
  textColor,
  textDecoration,
  textDecorationColor,
  textDecorationStyle,
  textDecorationThickness,
  textIndent,
  textOpacity,
  textOverflow,
  textTransform,
  textUnderlineOffset,
  textWrap,
  touchAction,
  transform,
  transformOrigin,
  transitionDelay,
  transitionDuration,
  transitionProperty,
  transitionTimingFunction,
  userSelect,
  verticalAlign,
  visibility,
  whitespace,
  width,
  willChange,
  wordBreak,
  zIndex,
  translate,
  screens,
} = require("tailwindcss/defaultTheme")

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class", "[data-theme='dark']"],
  content: [
    "./apps/prepare/src/**/*.{ts,tsx,js,jsx,astro}",
    "./apps/prepare/src/components/**/*.{ts,tsx,js,jsx,astro}",
    "./apps/prepare/src/pages/**/*.{ts,tsx,js,jsx,astro}",
    "./apps/www/**/*.{ts,tsx,js,jsx,astro}",
    "./apps/www/components/**/*.{ts,tsx,js,jsx,astro}",
    "./apps/www/registry/**/*.{ts,tsx,js,jsx,astro}",
    "./apps/www/registry/default/**/*.{ts,tsx,js,jsx,astro}",
    "./apps/www/registry/new-york/**/*.{ts,tsx,js,jsx,astro}",
    "./apps/www/registry/default/prodkt/**/*.{ts,tsx,js,jsx,astro}",
    "./apps/www/registry/new-york/prodkt/**/*.{ts,tsx,js,jsx,astro}",
  ],
  theme: {
    extend: {
      translate: {
        ...translate,
        "top-48": "-48%",
      },
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        "foreground-hover": "var(--foreground-hover)",
        "foreground-active": "var(--foreground-active)",
        "foreground-selected": "var(--foreground-selected)",
        input: {
          DEFAULT: "var(--input)",
          hover: "var(--input-hover)",
          active: "var(--input-active)",
          disabled: "var(--input-disabled)",
          selected: "var(--input-selected)",
        },
        ring: {
          DEFAULT: "var(--ring)",
          hover: "var(--ring-hover)",
          active: "var(--ring-active)",
          disabled: "var(--ring-disabled)",
          selected: "var(--ring-selected)",
        },
        border: {
          DEFAULT: "var(--border)",
          hover: "var(--border-hover)",
          active: "var(--border-active)",
          disabled: "var(--border-disabled)",
          selected: "var(--border-selected)",
        },
        link: {
          DEFAULT: "var(--link)",
          hover: "var(--link-hover)",
          active: "var(--link-active)",
          disabled: "var(--link-disabled)",
          selected: "var(--link-selected)",
        },
        brand: {
          DEFAULT: "var(--brand)",
          hover: "var(--brand-hover)",
          active: "var(--brand-active)",
          selected: "var(--brand-selected)",
          focus: "var(--brand-focus)",
          disabled: "var(--brand-disabled)",
          inverse: "var(--brand-inverse)",
          "inverse-hover": "var(--brand-inverse-hover)",
          "inverse-active": "var(--brand-inverse-active)",
          "inverse-selected": "var(--brand-inverse-selected)",
          "inverse-focus": "var(--brand-inverse-focus)",
          "inverse-disabled": "var(--brand-inverse-disabled)",
          text: "var(--brand-text)",
          "text-inverse": "var(--brand-text-inverse)",
          foreground: "var(--brand-foreground)",
          "foreground-inverse": "var(--brand-foreground-inverse)",
          1: "var(--brand-1)",
          2: "var(--brand-2)",
          3: "var(--brand-3)",
          4: "var(--brand-4)",
          5: "var(--brand-5)",
          6: "var(--brand-6)",
          7: "var(--brand-7)",
          8: "var(--brand-8)",
          9: "var(--brand-9)",
          10: "var(--brand-10)",
          11: "var(--brand-11)",
          12: "var(--brand-12)",
          a1: "var(--brand-a1)",
          a2: "var(--brand-a2)",
          a3: "var(--brand-a3)",
          a4: "var(--brand-a4)",
          a5: "var(--brand-a5)",
          a6: "var(--brand-a6)",
          a7: "var(--brand-a7)",
          a8: "var(--brand-a8)",
          a9: "var(--brand-a9)",
          a10: "var(--brand-a10)",
          a11: "var(--brand-a11)",
          a12: "var(--brand-a12)",
        },
        primary: {
          DEFAULT: "var(--primary)",
          hover: "var(--primary-hover)",
          active: "var(--primary-active)",
          selected: "var(--primary-selected)",
          focus: "var(--primary-focus)",
          disabled: "var(--primary-disabled)",
          overlay: "var(--primary-overlay)",
          "overlay-hover": "var(--primary-overlay-hover)",
          "overlay-active": "var(--primary-overlay-active)",
          "overlay-selected": "var(--primary-overlay-selected)",
          muted: "var(--primary-muted)",
          "muted-hover": "var(--primary-muted-hover)",
          "muted-active": "var(--primary-muted-active)",
          "muted-selected": "var(--primary-muted-selected)",
          inverse: "var(--primary-inverse)",
          "inverse-hover": "var(--primary-inverse-hover)",
          "inverse-active": "var(--primary-inverse-active)",
          "inverse-selected": "var(--primary-inverse-selected)",
          "inverse-focus": "var(--primary-inverse-focus)",
          "inverse-disabled": "var(--primary-inverse-disabled)",
          text: "var(--primary-text)",
          "text-inverse": "var(--primary-text-inverse)",
          foreground: "var(--primary-foreground)",
          "foreground-hover": "var(--primary-foreground-hover)",
          "foreground-active": "var(--primary-foreground-active)",
          "foreground-selected": "var(--primary-foreground-selected)",
          "foreground-inverse": "var(--primary-foreground-inverse)",
          1: "var(--primary-1)",
          2: "var(--primary-2)",
          3: "var(--primary-3)",
          4: "var(--primary-4)",
          5: "var(--primary-5)",
          6: "var(--primary-6)",
          7: "var(--primary-7)",
          8: "var(--primary-8)",
          9: "var(--primary-9)",
          10: "var(--primary-10)",
          11: "var(--primary-11)",
          12: "var(--primary-12)",
          a1: "var(--primary-a1)",
          a2: "var(--primary-a2)",
          a3: "var(--primary-a3)",
          a4: "var(--primary-a4)",
          a5: "var(--primary-a5)",
          a6: "var(--primary-a6)",
          a7: "var(--primary-a7)",
          a8: "var(--primary-a8)",
          a9: "var(--primary-a9)",
          a10: "var(--primary-a10)",
          a11: "var(--primary-a11)",
          a12: "var(--primary-a12)",
        },
        amber: {
          1: "var(--amber-1)",
          2: "var(--amber-2)",
          3: "var(--amber-3)",
          4: "var(--amber-4)",
          5: "var(--amber-5)",
          6: "var(--amber-6)",
          7: "var(--amber-7)",
          8: "var(--amber-8)",
          9: "var(--amber-9)",
          10: "var(--amber-10)",
          11: "var(--amber-11)",
          12: "var(--amber-12)",
          a1: "var(--amber-a1)",
          a2: "var(--amber-a2)",
          a3: "var(--amber-a3)",
          a4: "var(--amber-a4)",
          a5: "var(--amber-a5)",
          a6: "var(--amber-a6)",
          a7: "var(--amber-a7)",
          a8: "var(--amber-a8)",
          a9: "var(--amber-a9)",
          a10: "var(--amber-a10)",
          a11: "var(--amber-a11)",
          a12: "var(--amber-a12)",
        },
        blue: {
          1: "var(--blue-1)",
          2: "var(--blue-2)",
          3: "var(--blue-3)",
          4: "var(--blue-4)",
          5: "var(--blue-5)",
          6: "var(--blue-6)",
          7: "var(--blue-7)",
          8: "var(--blue-8)",
          9: "var(--blue-9)",
          10: "var(--blue-10)",
          11: "var(--blue-11)",
          12: "var(--blue-12)",
          a1: "var(--blue-a1)",
          a2: "var(--blue-a2)",
          a3: "var(--blue-a3)",
          a4: "var(--blue-a4)",
          a5: "var(--blue-a5)",
          a6: "var(--blue-a6)",
          a7: "var(--blue-a7)",
          a8: "var(--blue-a8)",
          a9: "var(--blue-a9)",
          a10: "var(--blue-a10)",
          a11: "var(--blue-a11)",
          a12: "var(--blue-a12)",
        },
        bronze: {
          1: "var(--bronze-1)",
          2: "var(--bronze-2)",
          3: "var(--bronze-3)",
          4: "var(--bronze-4)",
          5: "var(--bronze-5)",
          6: "var(--bronze-6)",
          7: "var(--bronze-7)",
          8: "var(--bronze-8)",
          9: "var(--bronze-9)",
          10: "var(--bronze-10)",
          11: "var(--bronze-11)",
          12: "var(--bronze-12)",
          a1: "var(--bronze-a1)",
          a2: "var(--bronze-a2)",
          a3: "var(--bronze-a3)",
          a4: "var(--bronze-a4)",
          a5: "var(--bronze-a5)",
          a6: "var(--bronze-a6)",
          a7: "var(--bronze-a7)",
          a8: "var(--bronze-a8)",
          a9: "var(--bronze-a9)",
          a10: "var(--bronze-a10)",
          a11: "var(--bronze-a11)",
          a12: "var(--bronze-a12)",
        },
        brown: {
          1: "var(--brown-1)",
          2: "var(--brown-2)",
          3: "var(--brown-3)",
          4: "var(--brown-4)",
          5: "var(--brown-5)",
          6: "var(--brown-6)",
          7: "var(--brown-7)",
          8: "var(--brown-8)",
          9: "var(--brown-9)",
          10: "var(--brown-10)",
          11: "var(--brown-11)",
          12: "var(--brown-12)",
          a1: "var(--brown-a1)",
          a2: "var(--brown-a2)",
          a3: "var(--brown-a3)",
          a4: "var(--brown-a4)",
          a5: "var(--brown-a5)",
          a6: "var(--brown-a6)",
          a7: "var(--brown-a7)",
          a8: "var(--brown-a8)",
          a9: "var(--brown-a9)",
          a10: "var(--brown-a10)",
          a11: "var(--brown-a11)",
          a12: "var(--brown-a12)",
        },
        crimson: {
          1: "var(--crimson-1)",
          2: "var(--crimson-2)",
          3: "var(--crimson-3)",
          4: "var(--crimson-4)",
          5: "var(--crimson-5)",
          6: "var(--crimson-6)",
          7: "var(--crimson-7)",
          8: "var(--crimson-8)",
          9: "var(--crimson-9)",
          10: "var(--crimson-10)",
          11: "var(--crimson-11)",
          12: "var(--crimson-12)",
          a1: "var(--crimson-a1)",
          a2: "var(--crimson-a2)",
          a3: "var(--crimson-a3)",
          a4: "var(--crimson-a4)",
          a5: "var(--crimson-a5)",
          a6: "var(--crimson-a6)",
          a7: "var(--crimson-a7)",
          a8: "var(--crimson-a8)",
          a9: "var(--crimson-a9)",
          a10: "var(--crimson-a10)",
          a11: "var(--crimson-a11)",
          a12: "var(--crimson-a12)",
        },
        cyan: {
          1: "var(--cyan-1)",
          2: "var(--cyan-2)",
          3: "var(--cyan-3)",
          4: "var(--cyan-4)",
          5: "var(--cyan-5)",
          6: "var(--cyan-6)",
          7: "var(--cyan-7)",
          8: "var(--cyan-8)",
          9: "var(--cyan-9)",
          10: "var(--cyan-10)",
          11: "var(--cyan-11)",
          12: "var(--cyan-12)",
          a1: "var(--cyan-a1)",
          a2: "var(--cyan-a2)",
          a3: "var(--cyan-a3)",
          a4: "var(--cyan-a4)",
          a5: "var(--cyan-a5)",
          a6: "var(--cyan-a6)",
          a7: "var(--cyan-a7)",
          a8: "var(--cyan-a8)",
          a9: "var(--cyan-a9)",
          a10: "var(--cyan-a10)",
          a11: "var(--cyan-a11)",
          a12: "var(--cyan-a12)",
        },
        gold: {
          1: "var(--gold-1)",
          2: "var(--gold-2)",
          3: "var(--gold-3)",
          4: "var(--gold-4)",
          5: "var(--gold-5)",
          6: "var(--gold-6)",
          7: "var(--gold-7)",
          8: "var(--gold-8)",
          9: "var(--gold-9)",
          10: "var(--gold-10)",
          11: "var(--gold-11)",
          12: "var(--gold-12)",
          a1: "var(--gold-a1)",
          a2: "var(--gold-a2)",
          a3: "var(--gold-a3)",
          a4: "var(--gold-a4)",
          a5: "var(--gold-a5)",
          a6: "var(--gold-a6)",
          a7: "var(--gold-a7)",
          a8: "var(--gold-a8)",
          a9: "var(--gold-a9)",
          a10: "var(--gold-a10)",
          a11: "var(--gold-a11)",
          a12: "var(--gold-a12)",
        },
        grass: {
          1: "var(--grass-1)",
          2: "var(--grass-2)",
          3: "var(--grass-3)",
          4: "var(--grass-4)",
          5: "var(--grass-5)",
          6: "var(--grass-6)",
          7: "var(--grass-7)",
          8: "var(--grass-8)",
          9: "var(--grass-9)",
          10: "var(--grass-10)",
          11: "var(--grass-11)",
          12: "var(--grass-12)",
          a1: "var(--grass-a1)",
          a2: "var(--grass-a2)",
          a3: "var(--grass-a3)",
          a4: "var(--grass-a4)",
          a5: "var(--grass-a5)",
          a6: "var(--grass-a6)",
          a7: "var(--grass-a7)",
          a8: "var(--grass-a8)",
          a9: "var(--grass-a9)",
          a10: "var(--grass-a10)",
          a11: "var(--grass-a11)",
          a12: "var(--grass-a12)",
        },
        green: {
          1: "var(--green-1)",
          2: "var(--green-2)",
          3: "var(--green-3)",
          4: "var(--green-4)",
          5: "var(--green-5)",
          6: "var(--green-6)",
          7: "var(--green-7)",
          8: "var(--green-8)",
          9: "var(--green-9)",
          10: "var(--green-10)",
          11: "var(--green-11)",
          12: "var(--green-12)",
          a1: "var(--green-a1)",
          a2: "var(--green-a2)",
          a3: "var(--green-a3)",
          a4: "var(--green-a4)",
          a5: "var(--green-a5)",
          a6: "var(--green-a6)",
          a7: "var(--green-a7)",
          a8: "var(--green-a8)",
          a9: "var(--green-a9)",
          a10: "var(--green-a10)",
          a11: "var(--green-a11)",
          a12: "var(--green-a12)",
        },
        indigo: {
          1: "var(--indigo-1)",
          2: "var(--indigo-2)",
          3: "var(--indigo-3)",
          4: "var(--indigo-4)",
          5: "var(--indigo-5)",
          6: "var(--indigo-6)",
          7: "var(--indigo-7)",
          8: "var(--indigo-8)",
          9: "var(--indigo-9)",
          10: "var(--indigo-10)",
          11: "var(--indigo-11)",
          12: "var(--indigo-12)",
          a1: "var(--indigo-a1)",
          a2: "var(--indigo-a2)",
          a3: "var(--indigo-a3)",
          a4: "var(--indigo-a4)",
          a5: "var(--indigo-a5)",
          a6: "var(--indigo-a6)",
          a7: "var(--indigo-a7)",
          a8: "var(--indigo-a8)",
          a9: "var(--indigo-a9)",
          a10: "var(--indigo-a10)",
          a11: "var(--indigo-a11)",
          a12: "var(--indigo-a12)",
        },
        iris: {
          1: "var(--iris-1)",
          2: "var(--iris-2)",
          3: "var(--iris-3)",
          4: "var(--iris-4)",
          5: "var(--iris-5)",
          6: "var(--iris-6)",
          7: "var(--iris-7)",
          8: "var(--iris-8)",
          9: "var(--iris-9)",
          10: "var(--iris-10)",
          11: "var(--iris-11)",
          12: "var(--iris-12)",
          a1: "var(--iris-a1)",
          a2: "var(--iris-a2)",
          a3: "var(--iris-a3)",
          a4: "var(--iris-a4)",
          a5: "var(--iris-a5)",
          a6: "var(--iris-a6)",
          a7: "var(--iris-a7)",
          a8: "var(--iris-a8)",
          a9: "var(--iris-a9)",
          a10: "var(--iris-a10)",
          a11: "var(--iris-a11)",
          a12: "var(--iris-a12)",
        },
        jade: {
          1: "var(--jade-1)",
          2: "var(--jade-2)",
          3: "var(--jade-3)",
          4: "var(--jade-4)",
          5: "var(--jade-5)",
          6: "var(--jade-6)",
          7: "var(--jade-7)",
          8: "var(--jade-8)",
          9: "var(--jade-9)",
          10: "var(--jade-10)",
          11: "var(--jade-11)",
          12: "var(--jade-12)",
          a1: "var(--jade-a1)",
          a2: "var(--jade-a2)",
          a3: "var(--jade-a3)",
          a4: "var(--jade-a4)",
          a5: "var(--jade-a5)",
          a6: "var(--jade-a6)",
          a7: "var(--jade-a7)",
          a8: "var(--jade-a8)",
          a9: "var(--jade-a9)",
          a10: "var(--jade-a10)",
          a11: "var(--jade-a11)",
          a12: "var(--jade-a12)",
        },
        lime: {
          1: "var(--lime-1)",
          2: "var(--lime-2)",
          3: "var(--lime-3)",
          4: "var(--lime-4)",
          5: "var(--lime-5)",
          6: "var(--lime-6)",
          7: "var(--lime-7)",
          8: "var(--lime-8)",
          9: "var(--lime-9)",
          10: "var(--lime-10)",
          11: "var(--lime-11)",
          12: "var(--lime-12)",
          a1: "var(--lime-a1)",
          a2: "var(--lime-a2)",
          a3: "var(--lime-a3)",
          a4: "var(--lime-a4)",
          a5: "var(--lime-a5)",
          a6: "var(--lime-a6)",
          a7: "var(--lime-a7)",
          a8: "var(--lime-a8)",
          a9: "var(--lime-a9)",
          a10: "var(--lime-a10)",
          a11: "var(--lime-a11)",
          a12: "var(--lime-a12)",
        },
        mauve: {
          1: "var(--mauve-1)",
          2: "var(--mauve-2)",
          3: "var(--mauve-3)",
          4: "var(--mauve-4)",
          5: "var(--mauve-5)",
          6: "var(--mauve-6)",
          7: "var(--mauve-7)",
          8: "var(--mauve-8)",
          9: "var(--mauve-9)",
          10: "var(--mauve-10)",
          11: "var(--mauve-11)",
          12: "var(--mauve-12)",
          a1: "var(--mauve-a1)",
          a2: "var(--mauve-a2)",
          a3: "var(--mauve-a3)",
          a4: "var(--mauve-a4)",
          a5: "var(--mauve-a5)",
          a6: "var(--mauve-a6)",
          a7: "var(--mauve-a7)",
          a8: "var(--mauve-a8)",
          a9: "var(--mauve-a9)",
          a10: "var(--mauve-a10)",
          a11: "var(--mauve-a11)",
          a12: "var(--mauve-a12)",
        },
        mint: {
          1: "var(--mint-1)",
          2: "var(--mint-2)",
          3: "var(--mint-3)",
          4: "var(--mint-4)",
          5: "var(--mint-5)",
          6: "var(--mint-6)",
          7: "var(--mint-7)",
          8: "var(--mint-8)",
          9: "var(--mint-9)",
          10: "var(--mint-10)",
          11: "var(--mint-11)",
          12: "var(--mint-12)",
          a1: "var(--mint-a1)",
          a2: "var(--mint-a2)",
          a3: "var(--mint-a3)",
          a4: "var(--mint-a4)",
          a5: "var(--mint-a5)",
          a6: "var(--mint-a6)",
          a7: "var(--mint-a7)",
          a8: "var(--mint-a8)",
          a9: "var(--mint-a9)",
          a10: "var(--mint-a10)",
          a11: "var(--mint-a11)",
          a12: "var(--mint-a12)",
        },
        olive: {
          1: "var(--olive-1)",
          2: "var(--olive-2)",
          3: "var(--olive-3)",
          4: "var(--olive-4)",
          5: "var(--olive-5)",
          6: "var(--olive-6)",
          7: "var(--olive-7)",
          8: "var(--olive-8)",
          9: "var(--olive-9)",
          10: "var(--olive-10)",
          11: "var(--olive-11)",
          12: "var(--olive-12)",
          a1: "var(--olive-a1)",
          a2: "var(--olive-a2)",
          a3: "var(--olive-a3)",
          a4: "var(--olive-a4)",
          a5: "var(--olive-a5)",
          a6: "var(--olive-a6)",
          a7: "var(--olive-a7)",
          a8: "var(--olive-a8)",
          a9: "var(--olive-a9)",
          a10: "var(--olive-a10)",
          a11: "var(--olive-a11)",
          a12: "var(--olive-a12)",
        },
        orange: {
          1: "var(--orange-1)",
          2: "var(--orange-2)",
          3: "var(--orange-3)",
          4: "var(--orange-4)",
          5: "var(--orange-5)",
          6: "var(--orange-6)",
          7: "var(--orange-7)",
          8: "var(--orange-8)",
          9: "var(--orange-9)",
          10: "var(--orange-10)",
          11: "var(--orange-11)",
          12: "var(--orange-12)",
          a1: "var(--orange-a1)",
          a2: "var(--orange-a2)",
          a3: "var(--orange-a3)",
          a4: "var(--orange-a4)",
          a5: "var(--orange-a5)",
          a6: "var(--orange-a6)",
          a7: "var(--orange-a7)",
          a8: "var(--orange-a8)",
          a9: "var(--orange-a9)",
          a10: "var(--orange-a10)",
          a11: "var(--orange-a11)",
          a12: "var(--orange-a12)",
        },
        pink: {
          1: "var(--pink-1)",
          2: "var(--pink-2)",
          3: "var(--pink-3)",
          4: "var(--pink-4)",
          5: "var(--pink-5)",
          6: "var(--pink-6)",
          7: "var(--pink-7)",
          8: "var(--pink-8)",
          9: "var(--pink-9)",
          10: "var(--pink-10)",
          11: "var(--pink-11)",
          12: "var(--pink-12)",
          a1: "var(--pink-a1)",
          a2: "var(--pink-a2)",
          a3: "var(--pink-a3)",
          a4: "var(--pink-a4)",
          a5: "var(--pink-a5)",
          a6: "var(--pink-a6)",
          a7: "var(--pink-a7)",
          a8: "var(--pink-a8)",
          a9: "var(--pink-a9)",
          a10: "var(--pink-a10)",
          a11: "var(--pink-a11)",
          a12: "var(--pink-a12)",
        },
        plum: {
          1: "var(--plum-1)",
          2: "var(--plum-2)",
          3: "var(--plum-3)",
          4: "var(--plum-4)",
          5: "var(--plum-5)",
          6: "var(--plum-6)",
          7: "var(--plum-7)",
          8: "var(--plum-8)",
          9: "var(--plum-9)",
          10: "var(--plum-10)",
          11: "var(--plum-11)",
          12: "var(--plum-12)",
          a1: "var(--plum-a1)",
          a2: "var(--plum-a2)",
          a3: "var(--plum-a3)",
          a4: "var(--plum-a4)",
          a5: "var(--plum-a5)",
          a6: "var(--plum-a6)",
          a7: "var(--plum-a7)",
          a8: "var(--plum-a8)",
          a9: "var(--plum-a9)",
          a10: "var(--plum-a10)",
          a11: "var(--plum-a11)",
          a12: "var(--plum-a12)",
        },
        purple: {
          1: "var(--purple-1)",
          2: "var(--purple-2)",
          3: "var(--purple-3)",
          4: "var(--purple-4)",
          5: "var(--purple-5)",
          6: "var(--purple-6)",
          7: "var(--purple-7)",
          8: "var(--purple-8)",
          9: "var(--purple-9)",
          10: "var(--purple-10)",
          11: "var(--purple-11)",
          12: "var(--purple-12)",
          a1: "var(--purple-a1)",
          a2: "var(--purple-a2)",
          a3: "var(--purple-a3)",
          a4: "var(--purple-a4)",
          a5: "var(--purple-a5)",
          a6: "var(--purple-a6)",
          a7: "var(--purple-a7)",
          a8: "var(--purple-a8)",
          a9: "var(--purple-a9)",
          a10: "var(--purple-a10)",
          a11: "var(--purple-a11)",
          a12: "var(--purple-a12)",
        },
        red: {
          1: "var(--red-1)",
          2: "var(--red-2)",
          3: "var(--red-3)",
          4: "var(--red-4)",
          5: "var(--red-5)",
          6: "var(--red-6)",
          7: "var(--red-7)",
          8: "var(--red-8)",
          9: "var(--red-9)",
          10: "var(--red-10)",
          11: "var(--red-11)",
          12: "var(--red-12)",
          a1: "var(--red-a1)",
          a2: "var(--red-a2)",
          a3: "var(--red-a3)",
          a4: "var(--red-a4)",
          a5: "var(--red-a5)",
          a6: "var(--red-a6)",
          a7: "var(--red-a7)",
          a8: "var(--red-a8)",
          a9: "var(--red-a9)",
          a10: "var(--red-a10)",
          a11: "var(--red-a11)",
          a12: "var(--red-a12)",
        },
        ruby: {
          1: "var(--ruby-1)",
          2: "var(--ruby-2)",
          3: "var(--ruby-3)",
          4: "var(--ruby-4)",
          5: "var(--ruby-5)",
          6: "var(--ruby-6)",
          7: "var(--ruby-7)",
          8: "var(--ruby-8)",
          9: "var(--ruby-9)",
          10: "var(--ruby-10)",
          11: "var(--ruby-11)",
          12: "var(--ruby-12)",
          a1: "var(--ruby-a1)",
          a2: "var(--ruby-a2)",
          a3: "var(--ruby-a3)",
          a4: "var(--ruby-a4)",
          a5: "var(--ruby-a5)",
          a6: "var(--ruby-a6)",
          a7: "var(--ruby-a7)",
          a8: "var(--ruby-a8)",
          a9: "var(--ruby-a9)",
          a10: "var(--ruby-a10)",
          a11: "var(--ruby-a11)",
          a12: "var(--ruby-a12)",
        },
        sage: {
          1: "var(--sage-1)",
          2: "var(--sage-2)",
          3: "var(--sage-3)",
          4: "var(--sage-4)",
          5: "var(--sage-5)",
          6: "var(--sage-6)",
          7: "var(--sage-7)",
          8: "var(--sage-8)",
          9: "var(--sage-9)",
          10: "var(--sage-10)",
          11: "var(--sage-11)",
          12: "var(--sage-12)",
          a1: "var(--sage-a1)",
          a2: "var(--sage-a2)",
          a3: "var(--sage-a3)",
          a4: "var(--sage-a4)",
          a5: "var(--sage-a5)",
          a6: "var(--sage-a6)",
          a7: "var(--sage-a7)",
          a8: "var(--sage-a8)",
          a9: "var(--sage-a9)",
          a10: "var(--sage-a10)",
          a11: "var(--sage-a11)",
          a12: "var(--sage-a12)",
        },
        sand: {
          1: "var(--sand-1)",
          2: "var(--sand-2)",
          3: "var(--sand-3)",
          4: "var(--sand-4)",
          5: "var(--sand-5)",
          6: "var(--sand-6)",
          7: "var(--sand-7)",
          8: "var(--sand-8)",
          9: "var(--sand-9)",
          10: "var(--sand-10)",
          11: "var(--sand-11)",
          12: "var(--sand-12)",
          a1: "var(--sand-a1)",
          a2: "var(--sand-a2)",
          a3: "var(--sand-a3)",
          a4: "var(--sand-a4)",
          a5: "var(--sand-a5)",
          a6: "var(--sand-a6)",
          a7: "var(--sand-a7)",
          a8: "var(--sand-a8)",
          a9: "var(--sand-a9)",
          a10: "var(--sand-a10)",
          a11: "var(--sand-a11)",
          a12: "var(--sand-a12)",
        },
        sky: {
          1: "var(--sky-1)",
          2: "var(--sky-2)",
          3: "var(--sky-3)",
          4: "var(--sky-4)",
          5: "var(--sky-5)",
          6: "var(--sky-6)",
          7: "var(--sky-7)",
          8: "var(--sky-8)",
          9: "var(--sky-9)",
          10: "var(--sky-10)",
          11: "var(--sky-11)",
          12: "var(--sky-12)",
          a1: "var(--sky-a1)",
          a2: "var(--sky-a2)",
          a3: "var(--sky-a3)",
          a4: "var(--sky-a4)",
          a5: "var(--sky-a5)",
          a6: "var(--sky-a6)",
          a7: "var(--sky-a7)",
          a8: "var(--sky-a8)",
          a9: "var(--sky-a9)",
          a10: "var(--sky-a10)",
          a11: "var(--sky-a11)",
          a12: "var(--sky-a12)",
        },
        slate: {
          1: "var(--slate-1)",
          2: "var(--slate-2)",
          3: "var(--slate-3)",
          4: "var(--slate-4)",
          5: "var(--slate-5)",
          6: "var(--slate-6)",
          7: "var(--slate-7)",
          8: "var(--slate-8)",
          9: "var(--slate-9)",
          10: "var(--slate-10)",
          11: "var(--slate-11)",
          12: "var(--slate-12)",
          a1: "var(--slate-a1)",
          a2: "var(--slate-a2)",
          a3: "var(--slate-a3)",
          a4: "var(--slate-a4)",
          a5: "var(--slate-a5)",
          a6: "var(--slate-a6)",
          a7: "var(--slate-a7)",
          a8: "var(--slate-a8)",
          a9: "var(--slate-a9)",
          a10: "var(--slate-a10)",
          a11: "var(--slate-a11)",
          a12: "var(--slate-a12)",
        },
        teal: {
          1: "var(--teal-1)",
          2: "var(--teal-2)",
          3: "var(--teal-3)",
          4: "var(--teal-4)",
          5: "var(--teal-5)",
          6: "var(--teal-6)",
          7: "var(--teal-7)",
          8: "var(--teal-8)",
          9: "var(--teal-9)",
          10: "var(--teal-10)",
          11: "var(--teal-11)",
          12: "var(--teal-12)",
          a1: "var(--teal-a1)",
          a2: "var(--teal-a2)",
          a3: "var(--teal-a3)",
          a4: "var(--teal-a4)",
          a5: "var(--teal-a5)",
          a6: "var(--teal-a6)",
          a7: "var(--teal-a7)",
          a8: "var(--teal-a8)",
          a9: "var(--teal-a9)",
          a10: "var(--teal-a10)",
          a11: "var(--teal-a11)",
          a12: "var(--teal-a12)",
        },
        tomato: {
          1: "var(--tomato-1)",
          2: "var(--tomato-2)",
          3: "var(--tomato-3)",
          4: "var(--tomato-4)",
          5: "var(--tomato-5)",
          6: "var(--tomato-6)",
          7: "var(--tomato-7)",
          8: "var(--tomato-8)",
          9: "var(--tomato-9)",
          10: "var(--tomato-10)",
          11: "var(--tomato-11)",
          12: "var(--tomato-12)",
          a1: "var(--tomato-a1)",
          a2: "var(--tomato-a2)",
          a3: "var(--tomato-a3)",
          a4: "var(--tomato-a4)",
          a5: "var(--tomato-a5)",
          a6: "var(--tomato-a6)",
          a7: "var(--tomato-a7)",
          a8: "var(--tomato-a8)",
          a9: "var(--tomato-a9)",
          a10: "var(--tomato-a10)",
          a11: "var(--tomato-a11)",
          a12: "var(--tomato-a12)",
        },
        violet: {
          1: "var(--violet-1)",
          2: "var(--violet-2)",
          3: "var(--violet-3)",
          4: "var(--violet-4)",
          5: "var(--violet-5)",
          6: "var(--violet-6)",
          7: "var(--violet-7)",
          8: "var(--violet-8)",
          9: "var(--violet-9)",
          10: "var(--violet-10)",
          11: "var(--violet-11)",
          12: "var(--violet-12)",
          a1: "var(--violet-a1)",
          a2: "var(--violet-a2)",
          a3: "var(--violet-a3)",
          a4: "var(--violet-a4)",
          a5: "var(--violet-a5)",
          a6: "var(--violet-a6)",
          a7: "var(--violet-a7)",
          a8: "var(--violet-a8)",
          a9: "var(--violet-a9)",
          a10: "var(--violet-a10)",
          a11: "var(--violet-a11)",
          a12: "var(--violet-a12)",
        },
        yellow: {
          1: "var(--yellow-1)",
          2: "var(--yellow-2)",
          3: "var(--yellow-3)",
          4: "var(--yellow-4)",
          5: "var(--yellow-5)",
          6: "var(--yellow-6)",
          7: "var(--yellow-7)",
          8: "var(--yellow-8)",
          9: "var(--yellow-9)",
          10: "var(--yellow-10)",
          11: "var(--yellow-11)",
          12: "var(--yellow-12)",
          a1: "var(--yellow-a1)",
          a2: "var(--yellow-a2)",
          a3: "var(--yellow-a3)",
          a4: "var(--yellow-a4)",
          a5: "var(--yellow-a5)",
          a6: "var(--yellow-a6)",
          a7: "var(--yellow-a7)",
          a8: "var(--yellow-a8)",
          a9: "var(--yellow-a9)",
          a10: "var(--yellow-a10)",
          a11: "var(--yellow-a11)",
          a12: "var(--yellow-a12)",
        },
        white: {
          DEFAULT: "var(--white-a9)",
          a1: "var(--white-a1)",
          a2: "var(--white-a2)",
          a3: "var(--white-a3)",
          a4: "var(--white-a4)",
          a5: "var(--white-a5)",
          a6: "var(--white-a6)",
          a7: "var(--white-a7)",
          a8: "var(--white-a8)",
          a9: "var(--white-a9)",
          a10: "var(--white-a10)",
          a11: "var(--white-a11)",
          a12: "var(--white-a12)",
        },
        black: {
          DEFAULT: "var(--black-a9)",
          a1: "var(--black-a1)",
          a2: "var(--black-a2)",
          a3: "var(--black-a3)",
          a4: "var(--black-a4)",
          a5: "var(--black-a5)",
          a6: "var(--black-a6)",
          a7: "var(--black-a7)",
          a8: "var(--black-a8)",
          a9: "var(--black-a9)",
          a10: "var(--black-a10)",
          a11: "var(--black-a11)",
          a12: "var(--black-a12)",
        },
        ghost: {
          a1: "var(--ghost-a1)",
          a2: "var(--ghost-a2)",
          a3: "var(--ghost-a3)",
          a4: "var(--ghost-a4)",
          a5: "var(--ghost-a5)",
          a6: "var(--ghost-a6)",
          a7: "var(--ghost-a7)",
          a8: "var(--ghost-a8)",
          a9: "var(--ghost-a9)",
          a10: "var(--ghost-a10)",
          a11: "var(--ghost-a11)",
          a12: "var(--ghost-a12)",
          aa1: "var(--ghost-aa1)",
          aa2: "var(--ghost-aa2)",
          aa3: "var(--ghost-aa3)",
          aa4: "var(--ghost-aa4)",
          aa5: "var(--ghost-aa5)",
          aa6: "var(--ghost-aa6)",
          aa7: "var(--ghost-aa7)",
          aa8: "var(--ghost-aa8)",
          aa9: "var(--ghost-aa9)",
          aa10: "var(--ghost-aa10)",
          aa11: "var(--ghost-aa11)",
          aa12: "var(--ghost-aa12)",
        },
        gray: {
          DEFAULT: "var(--gray)",
          hover: "var(--gray-hover)",
          active: "var(--gray-active)",
          selected: "var(--gray-selected)",
          focus: "var(--gray-focus)",
          disabled: "var(--gray-disabled)",
          inverse: "var(--gray-inverse)",
          "inverse-hover": "var(--gray-inverse-hover)",
          "inverse-active": "var(--gray-inverse-active)",
          "inverse-selected": "var(--gray-inverse-selected)",
          "inverse-focus": "var(--gray-inverse-focus)",
          "inverse-disabled": "var(--gray-inverse-disabled)",
          text: "var(--gray-text)",
          "text-inverse": "var(--gray-text-inverse)",
          foreground: "var(--gray-foreground)",
          "foreground-inverse": "var(--gray-foreground-inverse)",
          1: "var(--gray-1)",
          2: "var(--gray-2)",
          3: "var(--gray-3)",
          4: "var(--gray-4)",
          5: "var(--gray-5)",
          6: "var(--gray-6)",
          7: "var(--gray-7)",
          8: "var(--gray-8)",
          9: "var(--gray-9)",
          10: "var(--gray-10)",
          11: "var(--gray-11)",
          12: "var(--gray-12)",
          a1: "var(--gray-a1)",
          a2: "var(--gray-a2)",
          a3: "var(--gray-a3)",
          a4: "var(--gray-a4)",
          a5: "var(--gray-a5)",
          a6: "var(--gray-a6)",
          a7: "var(--gray-a7)",
          a8: "var(--gray-a8)",
          a9: "var(--gray-a9)",
          a10: "var(--gray-a10)",
          a11: "var(--gray-a11)",
          a12: "var(--gray-a12)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          hover: "var(--accent-hover)",
          active: "var(--accent-active)",
          selected: "var(--accent-selected)",
          focus: "var(--accent-focus)",
          disabled: "var(--accent-disabled)",
          inverse: "var(--accent-inverse)",
          "inverse-hover": "var(--accent-inverse-hover)",
          "inverse-active": "var(--accent-inverse-active)",
          "inverse-selected": "var(--accent-inverse-selected)",
          "inverse-focus": "var(--accent-inverse-focus)",
          "inverse-disabled": "var(--accent-inverse-disabled)",
          text: "var(--accent-text)",
          "text-inverse": "var(--accent-text-inverse)",
          foreground: "var(--accent-foreground)",
          "foreground-inverse": "var(--accent-foreground-inverse)",
          1: "var(--accent-1)",
          2: "var(--accent-2)",
          3: "var(--accent-3)",
          4: "var(--accent-4)",
          5: "var(--accent-5)",
          6: "var(--accent-6)",
          7: "var(--accent-7)",
          8: "var(--accent-8)",
          9: "var(--accent-9)",
          10: "var(--accent-10)",
          11: "var(--accent-11)",
          12: "var(--accent-12)",
          a1: "var(--accent-a1)",
          a2: "var(--accent-a2)",
          a3: "var(--accent-a3)",
          a4: "var(--accent-a4)",
          a5: "var(--accent-a5)",
          a6: "var(--accent-a6)",
          a7: "var(--accent-a7)",
          a8: "var(--accent-a8)",
          a9: "var(--accent-a9)",
          a10: "var(--accent-a10)",
          a11: "var(--accent-a11)",
          a12: "var(--accent-a12)",
        },
        destructive: {
          DEFAULT: "var(--destructive)",
          hover: "var(--destructive-hover)",
          active: "var(--destructive-active)",
          selected: "var(--destructive-selected)",
          focus: "var(--destructive-focus)",
          disabled: "var(--destructive-disabled)",
          inverse: "var(--destructive-inverse)",
          "inverse-hover": "var(--destructive-inverse-hover)",
          "inverse-active": "var(--destructive-inverse-active)",
          "inverse-selected": "var(--destructive-inverse-selected)",
          "inverse-focus": "var(--destructive-inverse-focus)",
          "inverse-disabled": "var(--destructive-inverse-disabled)",
          text: "var(--destructive-text)",
          "text-inverse": "var(--destructive-text-inverse)",
          foreground: "var(--destructive-foreground)",
          "foreground-inverse": "var(--destructive-foreground-inverse)",
          1: "var(--destructive-1)",
          2: "var(--destructive-2)",
          3: "var(--destructive-3)",
          4: "var(--destructive-4)",
          5: "var(--destructive-5)",
          6: "var(--destructive-6)",
          7: "var(--destructive-7)",
          8: "var(--destructive-8)",
          9: "var(--destructive-9)",
          10: "var(--destructive-10)",
          11: "var(--destructive-11)",
          12: "var(--destructive-12)",
          a1: "var(--destructive-a1)",
          a2: "var(--destructive-a2)",
          a3: "var(--destructive-a3)",
          a4: "var(--destructive-a4)",
          a5: "var(--destructive-a5)",
          a6: "var(--destructive-a6)",
          a7: "var(--destructive-a7)",
          a8: "var(--destructive-a8)",
          a9: "var(--destructive-a9)",
          a10: "var(--destructive-a10)",
          a11: "var(--destructive-a11)",
          a12: "var(--destructive-a12)",
        },
        warning: {
          DEFAULT: "var(--warning)",
          hover: "var(--warning-hover)",
          active: "var(--warning-active)",
          selected: "var(--warning-selected)",
          focus: "var(--warning-focus)",
          disabled: "var(--warning-disabled)",
          inverse: "var(--warning-inverse)",
          "inverse-hover": "var(--warning-inverse-hover)",
          "inverse-active": "var(--warning-inverse-active)",
          "inverse-selected": "var(--warning-inverse-selected)",
          "inverse-focus": "var(--warning-inverse-focus)",
          "inverse-disabled": "var(--warning-inverse-disabled)",
          text: "var(--warning-text)",
          "text-inverse": "var(--warning-text-inverse)",
          foreground: "var(--warning-foreground)",
          "foreground-inverse": "var(--warning-foreground-inverse)",
          1: "var(--warning-1)",
          2: "var(--warning-2)",
          3: "var(--warning-3)",
          4: "var(--warning-4)",
          5: "var(--warning-5)",
          6: "var(--warning-6)",
          7: "var(--warning-7)",
          8: "var(--warning-8)",
          9: "var(--warning-9)",
          10: "var(--warning-10)",
          11: "var(--warning-11)",
          12: "var(--warning-12)",
          a1: "var(--warning-a1)",
          a2: "var(--warning-a2)",
          a3: "var(--warning-a3)",
          a4: "var(--warning-a4)",
          a5: "var(--warning-a5)",
          a6: "var(--warning-a6)",
          a7: "var(--warning-a7)",
          a8: "var(--warning-a8)",
          a9: "var(--warning-a9)",
          a10: "var(--warning-a10)",
          a11: "var(--warning-a11)",
          a12: "var(--warning-a12)",
        },
        success: {
          DEFAULT: "var(--success)",
          hover: "var(--success-hover)",
          active: "var(--success-active)",
          selected: "var(--success-selected)",
          focus: "var(--success-focus)",
          disabled: "var(--success-disabled)",
          inverse: "var(--success-inverse)",
          "inverse-hover": "var(--success-inverse-hover)",
          "inverse-active": "var(--success-inverse-active)",
          "inverse-selected": "var(--success-inverse-selected)",
          "inverse-focus": "var(--success-inverse-focus)",
          "inverse-disabled": "var(--success-inverse-disabled)",
          text: "var(--success-text)",
          "text-inverse": "var(--success-text-inverse)",
          foreground: "var(--success-foreground)",
          "foreground-inverse": "var(--success-foreground-inverse)",
          1: "var(--success-1)",
          2: "var(--success-2)",
          3: "var(--success-3)",
          4: "var(--success-4)",
          5: "var(--success-5)",
          6: "var(--success-6)",
          7: "var(--success-7)",
          8: "var(--success-8)",
          9: "var(--success-9)",
          10: "var(--success-10)",
          11: "var(--success-11)",
          12: "var(--success-12)",
          a1: "var(--success-a1)",
          a2: "var(--success-a2)",
          a3: "var(--success-a3)",
          a4: "var(--success-a4)",
          a5: "var(--success-a5)",
          a6: "var(--success-a6)",
          a7: "var(--success-a7)",
          a8: "var(--success-a8)",
          a9: "var(--success-a9)",
          a10: "var(--success-a10)",
          a11: "var(--success-a11)",
          a12: "var(--success-a12)",
        },
        info: {
          DEFAULT: "var(--info)",
          hover: "var(--info-hover)",
          active: "var(--info-active)",
          selected: "var(--info-selected)",
          focus: "var(--info-focus)",
          disabled: "var(--info-disabled)",
          inverse: "var(--info-inverse)",
          "inverse-hover": "var(--info-inverse-hover)",
          "inverse-active": "var(--info-inverse-active)",
          "inverse-selected": "var(--info-inverse-selected)",
          "inverse-focus": "var(--info-inverse-focus)",
          "inverse-disabled": "var(--info-inverse-disabled)",
          text: "var(--info-text)",
          "text-inverse": "var(--info-text-inverse)",
          foreground: "var(--info-foreground)",
          "foreground-inverse": "var(--info-foreground-inverse)",
          1: "var(--info-1)",
          2: "var(--info-2)",
          3: "var(--info-3)",
          4: "var(--info-4)",
          5: "var(--info-5)",
          6: "var(--info-6)",
          7: "var(--info-7)",
          8: "var(--info-8)",
          9: "var(--info-9)",
          10: "var(--info-10)",
          11: "var(--info-11)",
          12: "var(--info-12)",
          a1: "var(--info-a1)",
          a2: "var(--info-a2)",
          a3: "var(--info-a3)",
          a4: "var(--info-a4)",
          a5: "var(--info-a5)",
          a6: "var(--info-a6)",
          a7: "var(--info-a7)",
          a8: "var(--info-a8)",
          a9: "var(--info-a9)",
          a10: "var(--info-a10)",
          a11: "var(--info-a11)",
          a12: "var(--info-a12)",
        },
        muted: {
          DEFAULT: "var(--muted)",
          hover: "var(--muted-hover)",
          active: "var(--muted-active)",
          selected: "var(--muted-selected)",
          focus: "var(--muted-focus)",
          disabled: "var(--muted-disabled)",
          inverse: "var(--muted-inverse)",
          "inverse-hover": "var(--muted-inverse-hover)",
          "inverse-active": "var(--muted-inverse-active)",
          "inverse-selected": "var(--muted-inverse-selected)",
          "inverse-focus": "var(--muted-inverse-focus)",
          "inverse-disabled": "var(--muted-inverse-disabled)",
          text: "var(--muted-text)",
          "text-inverse": "var(--muted-text-inverse)",
          foreground: "var(--muted-foreground)",
          "foreground-inverse": "var(--muted-foreground-inverse)",
        },
        popover: {
          DEFAULT: "var(--popover)",
          hover: "var(--popover-hover)",
          active: "var(--popover-active)",
          selected: "var(--popover-selected)",
          focus: "var(--popover-focus)",
          disabled: "var(--popover-disabled)",
          inverse: "var(--popover-inverse)",
          "inverse-hover": "var(--popover-inverse-hover)",
          "inverse-active": "var(--popover-inverse-active)",
          "inverse-selected": "var(--popover-inverse-selected)",
          "inverse-focus": "var(--popover-inverse-focus)",
          "inverse-disabled": "var(--popover-inverse-disabled)",
          text: "var(--popover-text)",
          "text-inverse": "var(--popover-text-inverse)",
          foreground: "var(--popover-foreground)",
          "foreground-inverse": "var(--popover-foreground-inverse)",
        },
        card: {
          DEFAULT: "var(--card)",
          "layer-1": "var(--card-layer-1)",
          hover: "var(--card-hover)",
          active: "var(--card-active)",
          selected: "var(--card-selected)",
          focus: "var(--card-focus)",
          disabled: "var(--card-disabled)",
          inverse: "var(--card-inverse)",
          "inverse-hover": "var(--card-inverse-hover)",
          "inverse-active": "var(--card-inverse-active)",
          "inverse-selected": "var(--card-inverse-selected)",
          "inverse-focus": "var(--card-inverse-focus)",
          "inverse-disabled": "var(--card-inverse-disabled)",
          text: "var(--card-text)",
          "text-inverse": "var(--card-text-inverse)",
          foreground: "var(--card-foreground)",
          "foreground-inverse": "var(--card-foreground-inverse)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          hover: "var(--secondary-hover)",
          active: "var(--secondary-active)",
          selected: "var(--secondary-selected)",
          focus: "var(--secondary-focus)",
          disabled: "var(--secondary-disabled)",
          overlay: "var(--secondary-overlay)",
          "overlay-hover": "var(--secondary-overlay-hover)",
          "overlay-active": "var(--secondary-overlay-active)",
          "overlay-selected": "var(--secondary-overlay-selected)",
          muted: "var(--secondary-muted)",
          "muted-hover": "var(--secondary-muted-hover)",
          "muted-active": "var(--secondary-muted-active)",
          "muted-selected": "var(--secondary-muted-selected)",
          inverse: "var(--secondary-inverse)",
          "inverse-hover": "var(--secondary-inverse-hover)",
          "inverse-active": "var(--secondary-inverse-active)",
          "inverse-selected": "var(--secondary-inverse-selected)",
          "inverse-focus": "var(--secondary-inverse-focus)",
          "inverse-disabled": "var(--secondary-inverse-disabled)",
          text: "var(--secondary-text)",
          "text-inverse": "var(--secondary-text-inverse)",
          foreground: "var(--secondary-foreground)",
          "foreground-hover": "var(--secondary-foreground-hover)",
          "foreground-active": "var(--secondary-foreground-active)",
          "foreground-selected": "var(--secondary-foreground-selected)",
          "foreground-inverse": "var(--secondary-foreground-inverse)",
          1: "var(--secondary-1)",
          2: "var(--secondary-2)",
          3: "var(--secondary-3)",
          4: "var(--secondary-4)",
          5: "var(--secondary-5)",
          6: "var(--secondary-6)",
          7: "var(--secondary-7)",
          8: "var(--secondary-8)",
          9: "var(--secondary-9)",
          10: "var(--secondary-10)",
          11: "var(--secondary-11)",
          12: "var(--secondary-12)",
          a1: "var(--secondary-a1)",
          a2: "var(--secondary-a2)",
          a3: "var(--secondary-a3)",
          a4: "var(--secondary-a4)",
          a5: "var(--secondary-a5)",
          a6: "var(--secondary-a6)",
          a7: "var(--secondary-a7)",
          a8: "var(--secondary-a8)",
          a9: "var(--secondary-a9)",
          a10: "var(--secondary-a10)",
          a11: "var(--secondary-a11)",
          a12: "var(--secondary-a12)",
        },
        sidebar: {
          DEFAULT: "var(--sidebar-background)",
          foreground: "var(--sidebar-foreground)",
          primary: "var(--sidebar-primary)",
          "primary-foreground": "var(--sidebar-primary-foreground)",
          accent: "var(--sidebar-accent)",
          "accent-foreground": "var(--sidebar-accent-foreground)",
          border: "var(--sidebar-border)",
          ring: "var(--sidebar-ring)",
        },
      },
      transitionDelay: {
        ...transitionDelay,
        1200: "1200ms",
        1500: "1500ms",
      },
      borderRadius: {
        "4xl": "var(--radius-4xl)",
        "3xl": "var(--radius-3xl)",
        "2xl": "var(--radius-2xl)",
        xl: "var(--radius-xl)",
        lg: "var(--radius-lg)",
        md: "var(--radius-md)",
        sm: "var(--radius-sm)",
      },
      fontFamily: {
        sans: ["var(--font-sans)", ...fontFamily.sans],
        serif: ["var(--font-serif)", ...fontFamily.serif],
        mono: ["var(--font-mono)", ...fontFamily.mono],
        bahnschrift: ["Bahnschrift"],
        heading: ["var(--font-heading)"],
      },
      keyframes: {
        ...keyframes,
        "fade-up": {
          "0%": {
            opacity: "0",
            transform: "translateY(10px)",
          },
          "80%": {
            opacity: "0.6",
          },
          "100%": {
            opacity: "1",
            transform: "translateY(0px)",
          },
        },
        "fade-down": {
          "0%": {
            opacity: "0",
            transform: "translateY(-10px)",
          },
          "80%": {
            opacity: "0.6",
          },
          "100%": {
            opacity: "1",
            transform: "translateY(0px)",
          },
        },
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
        "packages-marquee-left": {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
        "packages-marquee-right": {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(50%)" },
        },
        "marquee-section-left": {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
        "marquee-section-right": {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(50%)" },
        },
        "opacity-reveal": {
          "0%": {
            opacity: 0,
          },
          "100%": {
            opacity: 1,
          },
        },
        "github-stars-border": {
          "0%": {
            transform: "translateX(-72px)",
          },
          "100%": {
            transform: "translateX(216px)",
          },
        },
        "github-stars-glow": {
          "0%": {
            transform: "translateX(0) scale(0.5)",
          },
          "50%": {
            transform: "translateX(78px) scale(0.75)",
          },
          "100%": {
            transform: "translateX(140px) scale(0.65)",
          },
        },
        "learner-badge-movement": {
          "0%": {
            transform:
              "translateX(0) rotateX(0deg) rotateY(0deg) rotateZ(0deg) scale(0.70) translateZ(0px)",
          },
          "50%": {
            transform:
              "translateX(-10px) rotateX(4deg) rotateY(0deg) rotateZ(2deg) scale(0.75) translateZ(0px)",
          },
          "100%": {
            transform:
              "translateX(2px) rotateX(17deg) rotateY(0deg) rotateZ(0deg) scale(0.70) translateZ(0px)",
          },
        },
        "keyboard-shortcut-movement": {
          "0%": {
            transform:
              "translateX(0) translateY(-3px) rotateX(0deg) rotateY(0deg) rotateZ(0deg) scale(1) translateZ(0px)",
          },
          "20%": {
            transform:
              "translateX(-3px) translateY(6px) rotateX(4deg) rotateY(0deg) rotateZ(2deg) scale(0.75) translateZ(0px)",
          },
          "60%": {
            transform:
              "translateX(-10px) translateY(-3px) rotateX(4deg) rotateY(0deg) rotateZ(12deg) scale(0.75) translateZ(0px)",
          },
          "100%": {
            transform:
              "translateX(15px) translateY(10px) rotateX(-17deg) rotateY(0deg) rotateZ(0deg) scale(0.80) translateZ(0px)",
          },
        },
        "onboarding-guide-movement": {
          "0%": {
            transform:
              "translateX(0) translateY(1px) rotateX(0deg) rotateY(1deg) rotateZ(1deg) scale(1) translateZ(1px)",
          },
          "40%": {
            transform:
              "translateX(1px) translateY(-1px) rotateX(-2deg) rotateY(2deg) rotateZ(2deg) scale(.95) translateZ(3px)",
          },
          "60%": {
            transform:
              "translateX(-1px) translateY(1px) rotateX(-2deg) rotateY(2deg) rotateZ(2.2deg) scale(0.98) translateZ(4px)",
          },
          "100%": {
            transform:
              "translateX(-2px) translateY(0px) rotateX(-1deg) rotateY(1deg) rotateZ(1deg) scale(0.96) translateZ(3px)",
          },
        },
        ripple: {
          "0%, 100%": {
            transform: "translate(-50%, -50%) scale(1)",
          },
          "50%": {
            transform: "translate(-50%, -50%) scale(0.9)",
          },
        },
        shine: {
          "0%": {
            "background-position": "0% 0%",
          },
          "50%": {
            "background-position": "100% 100%",
          },
          to: {
            "background-position": "0% 0%",
          },
        },
        marquee: {
          from: { transform: "translateX(0)" },
          to: { transform: "translateX(calc(-100% - var(--gap)))" },
        },
        "marquee-vertical": {
          from: { transform: "translateY(0)" },
          to: { transform: "translateY(calc(-100% - var(--gap)))" },
        },
        "logo-cloud": {
          from: { transform: "translateX(0)" },
          to: { transform: "translateX(calc(-100% - 0rem))" },
        },
        "logo-cloud-reverse": {
          from: { transform: "translateX(calc(-100% - 0rem))" },
          to: { transform: "translateX(0)" },
        },
      },
      animation: {
        ...animation,
        "fade-up": "fade-up 0.5s",
        "fade-down": "fade-down 0.5s",
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
        "packages-marquee-left": "packages-marquee-left 65s linear infinite",
        "packages-marquee-right": "packages-marquee-right 60s linear infinite",
        "marquee-section-left": "marquee-section-left 40s linear infinite",
        "marquee-section-right": "marquee-section-right 40s linear infinite",
        "opacity-reveal": "opacity-reveal 1s ease-in-out forwards",
        "github-stars-border":
          "github-stars-border 10s linear infinite alternate",
        "github-stars-glow": "github-stars-glow 10s linear infinite alternate",
        "learner-badge-movement":
          "learner-badge-movement 10s linear infinite alternate",
        "keyboard-shortcut-movement":
          "keyboard-shortcut-movement 20s linear infinite alternate",
        "onboarding-guide-movement":
          "onboarding-guide-movement 10s linear infinite alternate",
        spinSlow1x: "spin 20.25s linear infinite",
        spinSlow2x: "spin 22.25s linear infinite",
        spinSlow3x: "spin 24.25s linear infinite",
        spinSlow4x: "spin 26.25s linear infinite",
        ripple: "ripple var(--duration,2s) ease calc(var(--i, 0)*.2s) infinite",
        shine: "shine var(--duration) infinite linear",
        marquee: "marquee var(--duration) linear infinite",
        "marquee-vertical": "marquee-vertical var(--duration) linear infinite",
        "logo-cloud": "logo-cloud 190s linear infinite",
        "logo-cloud-reverse": "logo-cloud-reverse 150s linear infinite",
        "logo-cloud-slow": "logo-cloud 260s linear infinite",
        "logo-cloud-reverse-slow": "logo-cloud-reverse 200s linear infinite",
      },
      boxShadows: {
        xs: "0 1px 2px 0 rgba(18, 18, 23, 0.05)",
        sm: "0 1px 3px 0 rgba(18, 18, 23, 0.1), 0 1px 2px 0 rgba(18, 18, 23, 0.06)",
        md: "0px 2px 4px -1px rgba(18, 18, 23, 0.06), 0px 4px 6px -1px rgba(18, 18, 23, 0.08)",
        lg: "0px 4px 6px -2px rgba(18, 18, 23, 0.05), 0px 10px 15px -3px rgba(18, 18, 23, 0.08)",
        xl: "0px 10px 10px -5px rgba(18, 18, 23, 0.04), 0px 20px 25px -5px rgba(18, 18, 23, 0.10)",
        "2xl": "0px 25px 50px -12px rgba(18, 18, 23, 0.25)",
        overlay:
          "0px 2px 4px 0px rgba(18, 18, 23, 0.04), 0px 5px 8px 0px rgba(18, 18, 23, 0.04), 0px 10px 18px 0px rgba(18, 18, 23, 0.03), 0px 24px 48px 0px rgba(18, 18, 23, 0.03), 0px 0px 0px 1px rgba(18, 18, 23, 0.10)",
      },
      fontSize: {
        ...fontSize,
        xxs: [
          "0.625rem",
          {
            lineHeight: "1rem",
          },
        ],
        xs: [
          "0.75rem",
          {
            lineHeight: "1rem",
          },
        ],
        sm: [
          "0.875rem",
          {
            lineHeight: "1.25rem",
          },
        ],
        base: [
          "1rem",
          {
            lineHeight: "1.5rem",
          },
        ],
        lg: [
          "1.125rem",
          {
            lineHeight: "1.75rem",
          },
        ],
        xl: [
          "1.25rem",
          {
            lineHeight: "1.75rem",
          },
        ],
        "2xl": [
          "1.5rem",
          {
            lineHeight: "2rem",
          },
        ],
        "3xl": [
          "1.875rem",
          {
            lineHeight: "2.25rem",
          },
        ],
        "4xl": [
          "2.25rem",
          {
            lineHeight: "2.5rem",
          },
        ],
        "5xl": [
          "3rem",
          {
            lineHeight: "3.5rem",
            letterSpacing: "-0.075rem",
          },
        ],
        "6xl": [
          "3.75rem",
          {
            lineHeight: "4.5rem",
            letterSpacing: "-0.09375rem",
          },
        ],
        "7xl": [
          "4.5rem",
          {
            lineHeight: "5rem",
            letterSpacing: "-0.1125rem",
          },
        ],
        "8xl": [
          "6rem",
          {
            lineHeight: "6.5rem",
            letterSpacing: "-0.15rem",
          },
        ],
        "9xl": [
          "8rem",
          {
            lineHeight: "8rem",
            letterSpacing: "-0.2rem",
          },
        ],
      },
      fontWeight: {
        ...fontWeight,
        thin: "100",
        hairline: "100",
        extralight: "200",
        "extra-light": "200",
        light: "300",
        normal: "400",
        regular: "400",
        medium: "500",
        demibold: "600",
        semibold: "600",
        bold: "700",
        extrabold: "800",
        "extra-bold": "800",
        black: "900",
      },
      minWidth: {
        4: "16px",
        5: "20px",
        6: "24px",
        7: "28px",
        8: "32px",
        10: "40px",
        12: "48px",
        14: "56px",
        16: "64px",
        20: "80px",
        24: "96px",
      },
      backgroundImage: {
        noise: "url(/images/sparkstack/noise.webp)",
        "lighting-test": "url(/images/sparkstack/bg_lighting-test_1.avif)",
        "navigation-menu": [
          "linear-gradient(180deg, var(--popover) 0%, var(--popover-hover) 100%)",
          "url(/images/sparkstack/stars.webp)",
          "url(/images/sparkstack/noise.webp)",
        ],
        "marquee-section": [
          "url(/images/sparkstack/noise.webp)",
          "radial-gradient(50% 100% at 50% -40%, var(--primary-a4) 0%, var(--primary-a1) 100%)",
        ],
        "packages-marquee": [
          "url(/images/sparkstack/noise.webp)",
          "radial-gradient(50% 100% at 50% -60%, var(--primary-a4) 0%, var(--primary-a1) 100%)",
        ],
        "marquee-section-text":
          "linear-gradient(180deg, var(--gray-a12) 0%, var(--gray-a11) 100%)",
        "packages-marquee-text":
          "linear-gradient(180deg, var(--gray-a12) 0%, var(--gray-a11) 100%)",
        "logo-shuffle": [
          "url(/images/sparkstack/noise.webp)",
          "radial-gradient(50% 100% at 50% 50%, var(--primary-a7) 0%, var(--primary-a1) 100%)",
        ],
        "github-stars-gradient":
          "radial-gradient(260.41% 41.87% at 8.38% 50%, var(--orange-a9) 0%, var(--orange-a3) 100%)",
        "github-stars-text":
          "linear-gradient(180deg, var(--gray-a10) 0%, var(--gray-a12) 100%)",
        "creative-tab-slider-glow-red-dark": [
          "url(/landing-noise.webp)",
          "radial-gradient(50% 50% at 50% 50%, rgba(250, 56, 82, 0.15) 0%, rgba(250, 56, 82, 0.00) 100%)",
        ],
        "creative-tab-slider-glow-yellow-dark": [
          "url(/landing-noise.webp)",
          "radial-gradient(50% 50% at 50% 50%, rgba(249, 213, 31, 0.15) 0%, rgba(249, 213, 31, 0.00) 100%)",
        ],
        "creative-tab-slider-glow-orange-dark": [
          "url(/landing-noise.webp)",
          "radial-gradient(50% 50% at 50% 50%, rgba(249, 140, 31, 0.15) 0%, rgba(249, 140, 31, 0.00) 100%)",
        ],
        "creative-tab-slider-glow-cyan-dark": [
          "url(/landing-noise.webp)",
          "radial-gradient(50% 50% at 50% 50%, rgba(71, 209, 191, 0.15) 0%, rgba(71, 209, 191, 0.00) 100%)",
        ],
        "creative-tab-slider-glow-blue-dark": [
          "url(/landing-noise.webp)",
          "radial-gradient(50% 50% at 50% 50%, rgba(61, 184, 245, 0.15) 0%, rgba(61, 184, 245, 0.00) 100%)",
        ],
        "landing-sweet-spot-glow-indigo-dark": [
          "url(/landing-noise.webp)",
          "radial-gradient(50% 50% at 50% 50%, rgba(89, 89, 255, 0.15) 0%, rgba(89, 89, 255, 0.00) 100%)",
        ],
        "creative-tab-slider-glow-red-light": [
          "radial-gradient(50% 50% at 70% 0%, rgba(210, 45, 45, 0.05) 0%, rgba(210, 45, 45, 0.00) 100%)",
          "radial-gradient(50% 50% at 50% 50%, rgba(210, 45, 45, 0.15) 0%, rgba(210, 45, 45, 0.00) 100%)",
        ],
        "creative-tab-slider-glow-yellow-light": [
          "radial-gradient(50% 50% at 70% 0%, rgba(244, 106, 37, 0.05) 0%, rgba(244, 106, 37, 0.00) 100%)",
          "radial-gradient(50% 50% at 50% 50%, rgba(244, 106, 37, 0.15) 0%, rgba(244, 106, 37, 0.00) 100%)",
        ],
        "creative-tab-slider-glow-orange-light": [
          "radial-gradient(50% 50% at 70% 0%, rgba(255, 159, 26, 0.05) 0%, rgba(255, 159, 26, 0.00) 100%)",
          "radial-gradient(50% 50% at 50% 50%, rgba(255, 159, 26, 0.15) 0%, rgba(255, 159, 26, 0.00) 100%)",
        ],
        "creative-tab-slider-glow-cyan-light": [
          "radial-gradient(50% 50% at 70% 0%, rgba(8, 145, 145, 0.05) 0%, rgba(8, 145, 145, 0.00) 100%)",
          "radial-gradient(50% 50% at 50% 50%, rgba(8, 145, 145, 0.15) 0%, rgba(8, 145, 145, 0.00) 100%)",
        ],
        "creative-tab-slider-glow-blue-light": [
          "radial-gradient(50% 50% at 70% 0%, rgba(31, 128, 224, 0.05) 0%, rgba(31, 128, 224, 0.00) 100%)",
          "radial-gradient(50% 50% at 50% 50%, rgba(31, 128, 224, 0.15) 0%, rgba(31, 128, 224, 0.00) 100%)",
        ],
        "creative-tab-slider-glow-indigo-light": [
          "radial-gradient(50% 50% at 70% 0%, rgba(105, 59, 198, 0.05) 0%, rgba(105, 59, 198, 0.00) 100%)",
          "radial-gradient(50% 50% at 50% 50%, rgba(105, 59, 198, 0.15) 0%, rgba(105, 59, 198, 0.00) 100%)",
        ],
        "radial-gradient-1":
          "radial-gradient(87.07% 87.07% at 52.38% 100%, var(--gray-a1) 0%, var(--gray-a6) 100%)",
        "radial-gradient-2":
          "radial-gradient(100.44% 141.42% at 0% 0%, var(--gray-a1) 0%, var(--gray-a6) 100%);",
        "radial-gradient": "radial-gradient(var(--tw-gradient-stops));",
        "conic-gradient":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      dropShadow: {
        ...dropShadow,
        "github-stars-glow": [
          "0px 0px 3px #FF993330",
          "0px 0px 6px #FF9933A0",
          "0px 0px 16px #FF9933A0",
          "0px 0px 16px #FF9933",
        ],
        "learner-badge-glow": [
          "0px 0px 3px var(--ghost-a1)",
          "0px 0px 6px var(--ghost-a1)",
          "0px 0px 16px var(--ghost-a1)",
          "0px 0px 16px var(--ghost-a1)",
        ],
      },
      backgroundSize: {
        ...backgroundSize,
        "github-stars-border-bg-size": "72px 72px",
        "creative-tab-slider-glow-size-lg": "auto auto, 1600px 1600px",
        "creative-tab-slider-glow-size-xs": "auto auto, 656px 656px",
      },
      backgroundPosition: {
        ...backgroundPosition,
        "landing-hero-bryan-bg-position":
          "center, calc(50% + 800px) calc(50% - 300px)",
        "creative-tab-slider-glow-position-lg":
          "center, calc(50% + 800px) calc(50% - 300px)",
        "creative-tab-slider-glow-position-md":
          "center, calc(50% + 490px) calc(50% + 180px)",
        "creative-tab-slider-glow-position-xs":
          "center, calc(50% - 30px) calc(50% + 300px)",
      },
      screens: {
        ...screens,
        "content-sm": "480px",
        "widening-start": "544px",
        "content-md": "656px",
        "content-xm": "768px",
        "content-xl": "792px",
        "content-xl-safe": "1376px",
        "content-2xl": "864px",
        "content-4xl": "1536px",
        "header-sm": "640px",
        "header-md": "1200px",
        "landing-content": "944px",
        "landing-xs": "360px",
        xs: "360px",
        "landing-sm": "720px",
        "landing-md": "960px",
        "landing-lg": "1296px",
        "landing-xl": "1440px",
        "tutorial-sm": "720px",
        "tutorial-md": "960px",
        "tutorial-lg": "1440px",
        "landing-footer": "1264px",
        "blog-sm": "592px",
        "blog-md": "720px",
        "blog-lg": "960px",
        "blog-max": "1296px",
        "blog-xl": "1440px",
        "blog-2xl": "1600px",
        walkthrough: "976px",
        "doc-form-lg": "824px",
        "doc-form-md": "688px",
      },
      accessibility: {
        ...accessibility,
      },
      alignContent: {
        ...alignContent,
      },
      alignItems: {
        ...alignItems,
      },
      alignSelf: {
        ...alignSelf,
      },
      appearance: {
        ...appearance,
      },
      aspectRatio: {
        ...aspectRatio,
      },
      backdropBlur: {
        ...backdropBlur,
      },
      backdropBrightness: {
        ...backdropBrightness,
      },
      backdropContrast: {
        ...backdropContrast,
      },
      backdropFilter: {
        ...backdropFilter,
      },
      backdropGrayscale: {
        ...backdropGrayscale,
      },
      backdropHueRotate: {
        ...backdropHueRotate,
      },
      backdropInvert: {
        ...backdropInvert,
      },
      backdropOpacity: {
        ...backdropOpacity,
      },
      backdropSaturate: {
        ...backdropSaturate,
      },
      backdropSepia: {
        ...backdropSepia,
      },
      backgroundAttachment: {
        ...backgroundAttachment,
      },
      blur: {
        ...blur,
      },
      borderCollapse: {
        ...borderCollapse,
      },
      borderSpacing: {
        ...borderSpacing,
      },
      borderStyle: {
        ...borderStyle,
      },
      borderWidth: {
        ...borderWidth,
      },
      boxDecorationBreak: {
        ...boxDecorationBreak,
      },
      boxShadow: {
        ...boxShadow,
      },
      boxSizing: {
        ...boxSizing,
      },
      breakAfter: {
        ...breakAfter,
      },
      breakBefore: {
        ...breakBefore,
      },
      breakInside: {
        ...breakInside,
      },
      captionSide: {
        ...captionSide,
      },
      caretColor: {
        ...caretColor,
      },
      clear: {
        ...clear,
      },
      columns: {
        ...columns,
      },
      contain: {
        ...contain,
      },
      container: {
        ...container,
      },
      content: {
        ...content,
      },
      contrast: {
        ...contrast,
      },
      cursor: {
        ...cursor,
      },
      display: {
        ...display,
      },
      divideOpacity: {
        ...divideOpacity,
      },
      divideStyle: {
        ...divideStyle,
      },
      divideWidth: {
        ...divideWidth,
      },
      fill: {
        ...fill,
      },
      filter: {
        ...filter,
      },
      flex: {
        ...flex,
      },
      flexBasis: {
        ...flexBasis,
      },
      flexDirection: {
        ...flexDirection,
      },
      flexGrow: {
        ...flexGrow,
      },
      flexShrink: {
        ...flexShrink,
      },
      flexWrap: {
        ...flexWrap,
      },
      float: {
        ...float,
      },
      fontStyle: {
        ...fontStyle,
      },
      fontVariantNumeric: {
        ...fontVariantNumeric,
      },
      forcedColorAdjust: {
        ...forcedColorAdjust,
      },
      grayscale: {
        ...grayscale,
      },
      gridAutoColumns: {
        ...gridAutoColumns,
      },
      gridAutoFlow: {
        ...gridAutoFlow,
      },
      gridAutoRows: {
        ...gridAutoRows,
      },
      gridColumn: {
        ...gridColumn,
      },
      gridColumnEnd: {
        ...gridColumnEnd,
      },
      gridColumnStart: {
        ...gridColumnStart,
      },
      gridRow: {
        ...gridRow,
      },
      gridRowEnd: {
        ...gridRowEnd,
      },
      gridTemplateColumns: {
        ...gridTemplateColumns,
      },
      gridTemplateRows: {
        ...gridTemplateRows,
      },
      height: {
        ...height,
      },
      hyphens: {
        ...hyphens,
      },
      inset: {
        ...inset,
      },
      invert: {
        ...invert,
      },
      isolation: {
        ...isolation,
      },
      justifyContent: {
        ...justifyContent,
      },
      justifyItems: {
        ...justifyItems,
      },
      justifySelf: {
        ...justifySelf,
      },
      letterSpacing: {
        ...letterSpacing,
      },
      lineClamp: {
        ...lineClamp,
      },
      lineHeight: {
        ...lineHeight,
      },
      listStyleImage: {
        ...listStyleImage,
      },
      listStylePosition: {
        ...listStylePosition,
      },
      listStyleType: {
        ...listStyleType,
      },
      margin: {
        ...margin,
      },
      maxHeight: {
        ...maxHeight,
      },
      maxWidth: {
        ...maxWidth,
      },
      minHeight: {
        ...minHeight,
      },
      mixBlendMode: {
        ...mixBlendMode,
      },
      objectFit: {
        ...objectFit,
      },
      objectPosition: {
        ...objectPosition,
      },
      opacity: {
        ...opacity,
      },
      order: {
        ...order,
      },
      outlineOffset: {
        ...outlineOffset,
      },
      outlineStyle: {
        ...outlineStyle,
      },
      outlineWidth: {
        ...outlineWidth,
      },
      overflow: {
        ...overflow,
      },
      overscrollBehavior: {
        ...overscrollBehavior,
      },
      padding: {
        ...padding,
      },
      placeContent: {
        ...placeContent,
      },
      placeItems: {
        ...placeItems,
      },
      placeSelf: {
        ...placeSelf,
      },
      placeholderOpacity: {
        ...placeholderOpacity,
      },
      pointerEvents: {
        ...pointerEvents,
      },
      position: {
        ...position,
      },
      preflight: {
        ...preflight,
      },
      resize: {
        ...resize,
      },
      ringOffsetWidth: {
        ...ringOffsetWidth,
      },
      ringOpacity: {
        ...ringOpacity,
      },
      ringWidth: {
        ...ringWidth,
      },
      rotate: {
        ...rotate,
      },
      saturate: {
        ...saturate,
      },
      scale: {
        ...scale,
      },
      scrollBehavior: {
        ...scrollBehavior,
      },
      scrollMargin: {
        ...scrollMargin,
      },
      scrollPadding: {
        ...scrollPadding,
      },
      scrollSnapAlign: {
        ...scrollSnapAlign,
      },
      scrollSnapStop: {
        ...scrollSnapStop,
      },
      scrollSnapType: {
        ...scrollSnapType,
      },
      sepia: {
        ...sepia,
      },
      size: {
        ...size,
      },
      skew: {
        ...skew,
      },
      space: {
        ...space,
      },
      stroke: {
        ...stroke,
      },
      spacing: {
        ...spacing,
      },
      strokeWidth: {
        ...strokeWidth,
      },
      tableLayout: {
        ...tableLayout,
      },
      textAlign: {
        ...textAlign,
      },
      textDecoration: {
        ...textDecoration,
      },
      textDecorationStyle: {
        ...textDecorationStyle,
      },
      textDecorationThickness: {
        ...textDecorationThickness,
      },
      textIndent: {
        ...textIndent,
      },
      textOpacity: {
        ...textOpacity,
      },
      textOverflow: {
        ...textOverflow,
      },
      textTransform: {
        ...textTransform,
      },
      textUnderlineOffset: {
        ...textUnderlineOffset,
      },
      textWrap: {
        ...textWrap,
      },
      touchAction: {
        ...touchAction,
      },
      transform: {
        ...transform,
      },
      transformOrigin: {
        ...transformOrigin,
      },
      transitionDuration: {
        ...transitionDuration,
      },
      transitionProperty: {
        ...transitionProperty,
      },
      transitionTimingFunction: {
        ...transitionTimingFunction,
      },
      userSelect: {
        ...userSelect,
      },
      verticalAlign: {
        ...verticalAlign,
      },
      visibility: {
        ...visibility,
      },
      whitespace: {
        ...whitespace,
      },
      width: {
        ...width,
      },
      willChange: {
        ...willChange,
      },
      wordBreak: {
        ...wordBreak,
      },
      zIndex: {
        ...zIndex,
      },
    },
    corePlugins: {
      aspectRatio: false,
    },
  },
  plugins: [
    // require("@tailwindcss/forms"),
    require("@tailwindcss/aspect-ratio"),
    require("@tailwindcss/container-queries"),
    require("@tailwindcss/typography"),
    prodktMotion,
  ],
} satisfies Config
